### ISSUE TITLE
Crash on Forge 1381

### ISSUE THREAD

**Issue by spannerman79** [MineMaarten/IGW-mod#26]
Forge: 1381
IWG: 1.1.3-18 (taken from mcmod.info)

Crash on client side.  This particular snippet is what makes minecraft run to momma :P 

    Stacktrace:
    	at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:383)
    	at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:238)
    	at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:456)
    	at igwmod.ClientProxy.addDefaultKeys(ClientProxy.java:108)
    	at igwmod.ClientProxy.postInit(ClientProxy.java:86)
    	at igwmod.IGWMod.postInit(IGWMod.java:97)

Full crash logs can be viewed via https://www.dropbox.com/sh/mg0usmyjstlu3wt/AADKzfcD-uyvltNyHjRMSabfa?dl=0

**Comment by sandalle** [comment]
I'm also seeing this with Forge 1448 and IGW-Mod 1.1.3-18. See also #25 as we are using MineTweaker3 3.0.9C.
