### ISSUE TITLE
Client crash to desktop when clicking Pressure Chamber entry

### ISSUE THREAD

**Issue by Axylxys** [MineMaarten/IGW-mod#29]
Here's the log, seems to work fine with other entries (i cut out the log spam, tell me if you need more details).

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/28/15 3:19 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at igwmod.WikiUtils.getNameFromStack(WikiUtils.java:49)
	at pneumaticCraft.common.thirdparty.igwmod.IntegratorPressureChamber.onCommandInvoke(IntegratorPressureChamber.java:65)
	at igwmod.InfoSupplier.decomposeTemplate(InfoSupplier.java:266)
	at igwmod.InfoSupplier.analyseInfo(InfoSupplier.java:131)
	at igwmod.gui.GuiWiki.updateWikiPage(GuiWiki.java:585)
	at igwmod.gui.GuiWiki.setCurrentFile(GuiWiki.java:246)
	at igwmod.gui.LocatedString.onMouseClick(LocatedString.java:85)
	at igwmod.gui.GuiWiki.func_73864_a(GuiWiki.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at igwmod.gui.GuiWiki.func_146274_d(GuiWiki.java:325)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at igwmod.WikiUtils.getNameFromStack(WikiUtils.java:49)
	at pneumaticCraft.common.thirdparty.igwmod.IntegratorPressureChamber.onCommandInvoke(IntegratorPressureChamber.java:65)
	at igwmod.InfoSupplier.decomposeTemplate(InfoSupplier.java:266)
	at igwmod.InfoSupplier.analyseInfo(InfoSupplier.java:131)
	at igwmod.gui.GuiWiki.updateWikiPage(GuiWiki.java:585)
	at igwmod.gui.GuiWiki.setCurrentFile(GuiWiki.java:246)
	at igwmod.gui.LocatedString.onMouseClick(LocatedString.java:85)
	at igwmod.gui.GuiWiki.func_73864_a(GuiWiki.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at igwmod.gui.GuiWiki.func_146274_d(GuiWiki.java:325)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: igwmod.gui.GuiWiki

**Comment by MineMaarten** [comment]
Fixed, as it's a duplicate with https://github.com/MineMaarten/PneumaticCraft/issues/507
